[package]
name = "procon-library"
version = "0.1.2"
edition = "2018"
authors = ["ne0san"]
license = "Apache-2.0"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
